# Generated by Django 5.1.6 on 2025-02-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userotp",
            name="otp_secret",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
