# Generated by Django 5.1.6 on 2025-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0004_user_is_email_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="organizations.Membership",
                to="organizations.organization",
            ),
        ),
    ]
