# Generated by Django 5.1.6 on 2025-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_organizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.TextField(),
        ),
    ]
