# Generated by Django 5.1.6 on 2025-03-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(),
        ),
    ]
