# Generated by Django 5.1.6 on 2025-03-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0001_initial"),
        ("organizations", "0007_alter_membership_role_alter_organization_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ["name"],
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturer's",
            },
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                help_text="Required field",
                max_length=255,
                verbose_name="Manufacturer's name",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manufacturers",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
    ]
