# Generated by Django 5.1.6 on 2025-04-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturers", "0002_alter_manufacturer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.TextField(
                help_text="Required field", verbose_name="Manufacturer's name"
            ),
        ),
    ]
