version: '3'

services:
  api:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DJANGO_SECRET_KEY: ${SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DJANGO_CORS_ALLOW_ALL_ORIGINS: ${CORS_ALLOW_ALL_ORIGINS}
      DJANGO_CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      DJANGO_CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      OAUTH_YANDEX_CLIENT_ID: ${OAUTH_YANDEX_CLIENT_ID}
      OAUTH_YANDEX_CLIENT_SECRET: ${OAUTH_YANDEX_CLIENT_SECRET}
    volumes:
      - static_volume:/app/static

volumes:
  static_volume: {}