# Generated by Django 5.1.6 on 2025-03-07 20:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("organizations", "0002_alter_organization_id"),
        ("organizations", "0003_organization_public_id_alter_organization_id"),
    ]

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
