# Generated by Django 5.1.6 on 2025-03-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_deleted_at_organization_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("default_permissions", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="membership",
            name="permission",
        ),
        migrations.AddField(
            model_name="membership",
            name="custom_permissions",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.role",
            ),
        ),
    ]
