# Generated by Django 5.1.6 on 2025-03-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_create_default_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.role",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.TextField(),
        ),
    ]
