# Generated by Django 5.1.6 on 2025-04-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_membership_role_alter_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Владелец"),
                    ("admin", "Администратор"),
                    ("manager", "Менеджер"),
                    ("staff", "Сотрудник"),
                ],
                default="staff",
                max_length=10,
            ),
        ),
        migrations.RenameField(
            model_name="membership",
            old_name="custom_permissions",
            new_name="permissions",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
