# Generated by Django 5.1.6 on 2025-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_alter_membership_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="permissions",
            field=models.PositiveBigIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
