# Generated by Django 5.1.6 on 2025-04-06 16:54

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0009_alter_membership_permissions"),
        ("registries", "0005_remove_manufacturer_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("receipt_name", models.TextField()),
                ("article", models.TextField(blank=True, null=True)),
                ("barcode", models.TextField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "max_discount",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("critical_stock", models.PositiveIntegerField(blank=True, null=True)),
                ("desired_stock", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "net_mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=16,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                    ),
                ),
                (
                    "gross_mass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=16,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="registries.category",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="registries.manufacturer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="organizations.organization",
                    ),
                ),
                (
                    "sales_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_sales_unit",
                        to="registries.measurementunit",
                    ),
                ),
                (
                    "write_off_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_write_off_unit",
                        to="registries.measurementunit",
                    ),
                ),
            ],
        ),
    ]
