# Generated by Django 5.1.6 on 2025-04-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_product_created_at_product_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="product",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sales_unit",
        ),
        migrations.RemoveField(
            model_name="product",
            name="write_off_unit",
        ),
    ]
