# Generated by Django 5.1.6 on 2025-04-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "documents",
            "0003_remove_product_category_remove_product_manufacturer_and_more",
        ),
        ("warehouses", "0006_product_alter_productstock_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
