# Generated by Django 5.2 on 2025-04-24 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
        ("registries", "0009_equipment_hourlywage"),
        (
            "warehouses",
            "0007_productstock_unique_productstock_warehouse_per_org_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, null=True, verbose_name="Название"),
                ),
                (
                    "member",
                    models.CharField(blank=True, null=True, verbose_name="Исполнитель"),
                ),
                (
                    "category",
                    models.CharField(blank=True, null=True, verbose_name="Категория"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Стоимость",
                    ),
                ),
                (
                    "norm_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Норма времени",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Максимальная скидка (%)",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Коэффициент",
                    ),
                ),
                (
                    "multiplicity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Кратность"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, null=True, verbose_name="Штрихкод"),
                ),
                (
                    "work_code",
                    models.CharField(blank=True, null=True, verbose_name="Код работы"),
                ),
                (
                    "hourly_wage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="works",
                        to="registries.hourlywage",
                        verbose_name="Нормочас",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="warehouses.product",
                        verbose_name="Номенкулатуры",
                    ),
                ),
                (
                    "related_works",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_to",
                        to="works.work",
                        verbose_name="Связанные работы",
                    ),
                ),
            ],
        ),
    ]
