# Generated by Django 5.1.7 on 2025-05-02 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0010_alter_membership_permissions_alter_membership_user'),
        ('registries', '0009_equipment_hourlywage'),
        ('warehouses', '0007_productstock_unique_productstock_warehouse_per_org_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('norm_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)])),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('multiplicity', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('barcode', models.TextField(blank=True, null=True)),
                ('work_code', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registries.category')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='organizations.membership')),
                ('hourly_wage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='registries.hourlywage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='organizations.organization')),
                ('products', models.ManyToManyField(blank=True, related_name='products', to='warehouses.product')),
                ('related_works', models.ManyToManyField(blank=True, related_name='related_to', to='works.work')),
            ],
        ),
    ]
