# Generated by Django 5.2 on 2025-04-26 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_membership_permissions_alter_membership_user'),
        ('registries', '0009_equipment_hourlywage'),
        ('warehouses', '0007_productstock_unique_productstock_warehouse_per_org_and_more'),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='member',
        ),
        migrations.AddField(
            model_name='work',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='organizations.membership'),
        ),
        migrations.AlterField(
            model_name='work',
            name='barcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registries.category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='hourly_wage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='registries.hourlywage'),
        ),
        migrations.AlterField(
            model_name='work',
            name='max_discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='work',
            name='multiplicity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='norm_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='work',
            name='product',
        ),
        migrations.AlterField(
            model_name='work',
            name='related_works',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='works.work'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='warehouses.product'),
        ),
    ]
