# Generated by Django 5.2 on 2025-04-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_work_member_work_executor_alter_work_barcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='product',
            new_name='products',
        ),
    ]
