# Generated by Django 5.1.6 on 2025-04-07 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_updated_at"),
        ("deals", "0002_deal_deleted_at_deal_is_deleted"),
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="organizations.organization",
            ),
        ),
    ]
