# Generated by Django 5.1.6 on 2025-04-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_car_frame_alter_car_license_plate_region_and_more"),
        ("deals", "0003_deal_created_at_deal_updated_at_alter_deal_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cars.car",
            ),
        ),
    ]
