# Generated by Django 5.1.6 on 2025-04-10 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_car_unique_car_vin_per_org_and_more"),
        ("clients", "0008_alter_client_organization"),
        ("deals", "0005_clientrequest"),
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
        ("registries", "0007_workplace"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientrequest",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"),
                name="unique_clientrequest_number_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"), name="unique_deal_number_per_org"
            ),
        ),
    ]
