# Generated by Django 5.1.6 on 2025-03-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_membership_role_alter_organization_name"),
        ("workplaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workplaces",
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workplace",
            name="icon",
            field=models.URLField(blank=True, null=True),
        ),
    ]
