# Generated by Django 5.1.6 on 2025-04-07 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplaces", "0002_workplace_organization_alter_workplace_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workplace",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
