export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "Содержит", value: "iLike" as const },
    { label: "Не содержит", value: "notILike" as const },
    { label: "Равно", value: "eq" as const },
    { label: "Не равно", value: "ne" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "Равно", value: "eq" as const },
    { label: "Не равно", value: "ne" as const },
    { label: "Меньше чем", value: "lt" as const },
    { label: "Меньше или равно", value: "lte" as const },
    { label: "Больше чем", value: "gt" as const },
    { label: "Больше или равно", value: "gte" as const },
    { label: "В диапазоне", value: "isBetween" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "Равно", value: "eq" as const },
    { label: "Не равно", value: "ne" as const },
    { label: "До", value: "lt" as const },
    { label: "После", value: "gt" as const },
    { label: "До или в", value: "lte" as const },
    { label: "После или в", value: "gte" as const },
    { label: "В диапазоне", value: "isBetween" as const },
    { label: "Относительно сегодня", value: "isRelativeToToday" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "Равно", value: "eq" as const },
    { label: "Не равно", value: "ne" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "Содержит любое из", value: "inArray" as const },
    { label: "Не содержит ни одного из", value: "notInArray" as const },
    { label: "Пусто", value: "isEmpty" as const },
    { label: "Не пусто", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "Равно", value: "eq" as const },
    { label: "Не равно", value: "ne" as const },
  ],
  sortOrders: [
    { label: "По возрастанию", value: "asc" as const },
    { label: "По убыванию", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};
