# Generated by Django 5.1.6 on 2025-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("year", models.PositiveIntegerField()),
                ("license_plate", models.CharField(max_length=15)),
                (
                    "license_plate_region",
                    models.CharField(
                        choices=[
                            ("ru", "RUS"),
                            ("by", "BY"),
                            ("kz", "KZ"),
                            ("am", "AM"),
                            ("az", "AZ"),
                            ("ge", "GE"),
                            ("kg", "KG"),
                            ("md", "MD"),
                            ("tj", "TJ"),
                            ("uz", "UZ"),
                            ("ee", "EST"),
                            ("lv", "LV"),
                            ("lt", "LT"),
                            ("ua", "UA"),
                            ("de", "D"),
                            ("fr", "F"),
                            ("us", "USA"),
                            ("cn", "CHN"),
                            ("jp", "J"),
                            ("tr", "TR"),
                            ("ch", "CH"),
                            ("pl", "PL"),
                            ("in", "IND"),
                        ],
                        max_length=5,
                    ),
                ),
                ("mileage", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
