# Generated by Django 5.1.6 on 2025-03-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="frame",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
