# Generated by Django 5.1.6 on 2025-03-25 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_color_car_frame"),
        ("organizations", "0007_alter_membership_role_alter_organization_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="car",
            name="frame",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
