# Generated by Django 5.1.6 on 2025-04-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_organization_alter_car_frame"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="license_plate_region",
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100),
        ),
    ]
