# Generated by Django 5.1.6 on 2025-04-02 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_car_brand_alter_car_license_plate_region_and_more"),
        ("registries", "0003_color_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.ForeignKey(
                blank=True,
                max_length=30,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registries.color",
            ),
        ),
    ]
