# Generated by Django 5.1.6 on 2025-04-04 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0005_alter_car_color"),
        ("registries", "0004_measurementunit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registries.color",
            ),
        ),
    ]
