# Generated by Django 5.1.6 on 2025-04-07 12:56

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_alter_car_color"),
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="frame",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="license_plate_region",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name="car",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="vin",
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ]
            ),
        ),
    ]
