# Generated by Django 5.1.6 on 2025-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0007_alter_car_frame_alter_car_license_plate_region_and_more"),
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
        ("registries", "0007_workplace"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("organization", "vin"), name="unique_car_vin_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("organization", "frame"), name="unique_car_frame_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="car",
            constraint=models.UniqueConstraint(
                fields=("organization", "license_plate"),
                name="unique_car_license_plate_per_org",
            ),
        ),
    ]
