# Generated by Django 5.2 on 2025-04-13 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0008_car_unique_car_vin_per_org_and_more"),
        ("clients", "0008_alter_client_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="clients.client",
            ),
        ),
    ]
