# Generated by Django 5.2 on 2025-04-26 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_car_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='license_plate_region',
        ),
    ]
