# Generated by Django 5.1.6 on 2025-04-02 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_membership_role_alter_organization_name"),
        ("registries", "0003_color_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.TextField()),
                ("abbreviation", models.CharField(max_length=100)),
                ("okei_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_units",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
