# Generated by Django 5.1.6 on 2025-04-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registries", "0004_measurementunit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manufacturer",
            name="is_deleted",
        ),
    ]
