# Generated by Django 5.1.6 on 2025-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
        ("registries", "0007_workplace"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_category_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="color",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_color_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_manufacturer_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementunit",
            constraint=models.UniqueConstraint(
                fields=("organization", "unit"),
                name="unique_measurementunit_unit_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurementunit",
            constraint=models.UniqueConstraint(
                fields=("organization", "abbreviation"),
                name="unique_measurementunit_abbreviation_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="workplace",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_workplace_name_per_org"
            ),
        ),
    ]
