# Generated by Django 5.1.6 on 2025-03-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_mileage_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='production_year',
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
