# Generated by Django 5.1.6 on 2025-03-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_client_created_at"),
        ("organizations", "0004_organization_deleted_at_organization_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
    ]
