# Generated by Django 5.1.6 on 2025-03-25 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_organization"),
        ("organizations", "0007_alter_membership_role_alter_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
