# Generated by Django 5.1.6 on 2025-04-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_client_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="client",
            name="middle_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(max_length=12),
        ),
    ]
