# Generated by Django 5.1.6 on 2025-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_client_first_name_alter_client_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
