# Generated by Django 5.1.6 on 2025-04-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_client_deleted_at_client_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
