# Generated by Django 5.1.6 on 2025-04-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_client_updated_at"),
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="organizations.organization",
            ),
        ),
    ]
