# Generated by Django 5.1.6 on 2025-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthprovider",
            name="provider",
            field=models.CharField(
                choices=[("yandex", "Yandex"), ("vk", "VK")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="oauthprovider",
            name="uid",
            field=models.TextField(unique=True),
        ),
    ]
