# Generated by Django 5.1.6 on 2025-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0002_alter_oauthprovider_provider_alter_oauthprovider_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="oauthprovider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
