# Generated by Django 5.1.6 on 2025-03-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('okei_code', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
    ]
