# Generated by Django 5.2 on 2025-05-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0008_car_unique_car_vin_per_org_and_more'),
        ('clients', '0008_alter_client_organization'),
        ('deals', '0006_clientrequest_unique_clientrequest_number_per_org_and_more'),
        ('organizations', '0010_alter_membership_permissions_alter_membership_user'),
        ('warehouses', '0007_productstock_unique_productstock_warehouse_per_org_and_more'),
        ('works', '0003_rename_product_work_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('calculation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='clients.client')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='deals.deal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='organizations.organization')),
                ('productStock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.productstock')),
                ('works', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculations', to='works.work')),
            ],
        ),
    ]
