# Generated by Django 5.1.6 on 2025-04-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
        ("warehouses", "0003_stockitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StockItem",
            new_name="ProductStock",
        ),
    ]
