# Generated by Django 5.1.6 on 2025-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_alter_membership_permissions_alter_membership_user"),
        ("warehouses", "0006_product_alter_productstock_product"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                fields=("organization", "warehouse"),
                name="unique_productstock_warehouse_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="productstock",
            constraint=models.UniqueConstraint(
                fields=("organization", "product"),
                name="unique_productstock_product_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_warehouse_name_per_org"
            ),
        ),
    ]
